### ISSUE TITLE
Currently supported functions

### ISSUE THREAD

**Issue by mat-l** [AsteroidOS/meta-dory-hybris#3]
Hello together,
I am watching the AsteroidOS project a since a while and I fthink it is a very interesting one. I own for myself a Huawei Watch, which is not yet maintained or supported yet. For a project I would like to buy the watch which is almost completely supported by AsteroidOS. Therefore I would like to ask you different things about the LG G Watch and it's currently available functions:

1. I can already write apps in C++ and QML, right?
2.1 Is Wifi supported?
2.2 Can I connect the phone to a classical Wifi router?
3. Is bluethooth supported?
4. When the battery is going low or the device restarts, then I have to transfer the image again to the watch?
5. Is the microphone already supported?

Thanks in advance :)
matl

**Comment by FlorentRevest** [comment]
Hi,

If you have some embeddded linux knowledge you can try to port AsteroidOS to your Huawei watch. Concerning the g watch:

1- Yes you can write apps in QML and C+
2.1, 2.2- There is no wifi chip on the G watch
2- Bluetooth is supported but largely in development so if you don't plan to develop it, don't expect to use it either.
3- No, the microphone is not supported at all

Florent

**Comment by TheLastProject** [comment]
To add to this, when the device restarts you'll only have to use the fastboot command again to make it boot from the AsteroidOS image. You don't have to push the full image again, only the fastboot part.
