### ISSUE TITLE
Notifications don't vibrate

### ISSUE THREAD

**Issue by 2Belette** [AsteroidOS/meta-dory-hybris#5]
Hi,

My LG G Watch is almost working correctly, only one remaining piece for a day to day use is this vibration issue. Clicking to the vibration button toggle the vibration correctly and the alarm clock / timer as well.
Receiving a notification doesn't vibrate, only the screen is showing the pop-up which makes notification very difficult to use as I need to always have an eye on my watch..

Many thanks for your great work!

**Comment by FlorentRevest** [comment]
Closed according to https://log.asteroidos.org/?date=2017-05-14&level=16
